version: '3.9'

services:
  orderservice:
    build:
      context: OrderService
      dockerfile: Dockerfile
      target: dev
    env_file:
      - .env.dev
    network_mode: host

    environment:
      - ConnectionStrings__DefaultConnection=${ORDER_DB_CONNECTION}
    volumes:
      - ./OrderService:/app
#      - /app/API/bin
#      - /app/API/obj
 

#    network_mode: "host"
      

#
#networks:
#  productnet: