version: '3.9'

services:
  productservice:
    build:
      context: ProductService
      dockerfile: Dockerfile
      target: dev
    env_file:
      - .env
    ports:
      - "5050:80"
    environment:
      - dbconn=${product-db-string}    
    volumes:
      - ./ProductService:/app
      - /app/API/bin   
      - /app/API/obj
    networks:
      - productnet
  orderservice:
    build:
      context: OrderService
      dockerfile: Dockerfile
      target: dev
    env_file:
      - .env
    ports:
      - "5051:80"
    environment:
      - dbconn=${order-db-string}
    volumes:
      - ./OrderService:/app
      - /app/API/bin
      - /app/API/obj
    networks:
      - productnet
networks:
  productnet: